// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test_tables.sql

package db

import (
	"context"
)

const createTestTable = `-- name: CreateTestTable :exec
INSERT INTO test_table (name) VALUES ('test')
`

func (q *Queries) CreateTestTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTestTable)
	return err
}
